In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('Lifeexpectancy.csv')
df.head()

population  fertility  HIV        CO2  BMI_male      GDP  BMI_female  life  \
0  34811059.0       2.73  0.1   3.328945  24.59620  12314.0    129.9049  75.3   
1  19842251.0       6.43  2.0   1.474353  22.25083   7103.0    130.1247  58.3   
2  40381860.0       2.24  0.5   4.785170  27.50170  14646.0    118.8915  75.5   
3   2975029.0       1.40  0.1   1.804106  25.35542   7383.0    132.8108  72.5   
4  21370348.0       1.96  0.1  18.016313  27.56373  41312.0    117.3755  81.5   

   child_mortality                      Region  
0             29.5  Middle East & North Africa  
1            192.0          Sub-Saharan Africa  
2             15.4                     America  
3             20.0       Europe & Central Asia  
4              5.2         East Asia & Pacific

In [2]:
k = df['life'].values
k

array([75.3, 58.3, 75.5, 72.5, 81.5, 80.4, 70.6, 72.2, 68.4, 75.3, 70.1,
       79.4, 70.7, 63.2, 67.6, 70.9, 61.2, 73.9, 73.2, 59.4, 57.4, 66.2,
       56.6, 80.7, 54.8, 78.9, 75.1, 62.6, 58.6, 79.7, 55.9, 76.5, 77.8,
       78.7, 61. , 74. , 70.1, 74.1, 56.7, 60.4, 74. , 65.7, 79.4, 81. ,
       57.5, 62.2, 72.1, 80. , 62.7, 79.5, 70.8, 58.3, 51.3, 63. , 61.7,
       70.9, 73.8, 82. , 64.4, 69.5, 76.9, 79.4, 80.9, 81.4, 75.5, 82.6,
       66.1, 61.5, 72.3, 77.6, 45.2, 61. , 72. , 80.7, 63.4, 51.4, 74.5,
       78.2, 55.8, 81.4, 63.6, 72.1, 75.7, 69.6, 63.2, 73.3, 55. , 60.8,
       68.6, 80.3, 80.2, 75.2, 59.7, 58. , 80.7, 74.6, 64.1, 77.1, 58.2,
       73.6, 76.8, 69.4, 75.3, 79.2, 80.4, 73.4, 67.6, 62.2, 64.3, 76.4,
       55.9, 80.9, 74.8, 78.5, 56.7, 55. , 81.1, 74.3, 67.4, 69.1, 46.1,
       81.1, 81.9, 69.5, 59.7, 74.1, 60. , 71.3, 76.5, 75.1, 57.2, 68.2,
       79.5, 78.2, 76. , 68.7, 75.4, 52. , 49. ])

In [3]:
l = df['fertility'].values
l

array([2.73, 6.43, 2.24, 1.4 , 1.96, 1.41, 1.99, 1.89, 2.38, 1.83, 1.42,
       1.82, 2.91, 5.27, 2.51, 3.48, 2.86, 1.9 , 1.43, 6.04, 6.48, 3.05,
       5.17, 1.68, 6.81, 1.89, 2.43, 5.05, 5.1 , 1.91, 4.91, 1.43, 1.5 ,
       1.89, 3.76, 2.73, 2.95, 2.32, 5.31, 5.16, 1.62, 2.74, 1.85, 1.97,
       4.28, 5.8 , 1.79, 1.37, 4.19, 1.46, 4.12, 5.34, 5.25, 2.74, 3.5 ,
       3.27, 1.33, 2.12, 2.64, 2.48, 1.88, 2.  , 2.92, 1.39, 2.39, 1.34,
       2.51, 4.76, 1.5 , 1.57, 3.34, 5.19, 1.42, 1.63, 4.79, 5.78, 2.05,
       2.38, 6.82, 1.38, 4.94, 1.58, 2.35, 1.49, 2.37, 2.44, 5.54, 2.05,
       2.9 , 1.77, 2.12, 2.72, 7.59, 6.02, 1.96, 2.89, 3.58, 2.61, 4.07,
       3.06, 2.58, 3.26, 1.33, 1.36, 2.2 , 1.34, 1.49, 5.06, 5.11, 1.41,
       5.13, 1.28, 1.31, 1.43, 7.06, 2.54, 1.42, 2.32, 4.79, 2.41, 3.7 ,
       1.92, 1.47, 3.7 , 5.54, 1.48, 4.88, 1.8 , 2.04, 2.15, 6.34, 1.38,
       1.87, 2.07, 2.11, 2.46, 1.86, 5.88, 3.85])

In [4]:
l=l.reshape(-1,1)

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
lin1=LinearRegression()

##### 1)Apply Linear Regression to the given dataset without splitting dataset


In [9]:
lin1.fit(l,k)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
y_predi=lin1.predict(l)
y_predi

array([70.82542398, 54.38307171, 73.00292468, 76.73578303, 74.2472108 ,
       76.69134424, 74.11389443, 74.55828233, 72.38078162, 74.82491507,
       76.64690545, 74.86935386, 70.02552576, 59.53797134, 71.80307735,
       67.49251473, 70.24771971, 74.51384354, 76.60246666, 56.11618452,
       54.16087776, 69.4033827 , 59.98235924, 75.49149691, 52.6943977 ,
       74.55828233, 72.15858767, 60.51562472, 60.29343077, 74.46940475,
       61.13776778, 76.60246666, 76.29139513, 74.55828233, 66.24822862,
       70.82542398, 69.8477706 , 72.64741436, 59.36021618, 60.02679803,
       75.75812965, 70.78098519, 74.73603749, 74.20277201, 63.93741154,
       57.18271548, 75.00267023, 76.8690994 , 64.33736065, 76.46915029,
       64.64843218, 59.22689981, 59.62684892, 70.78098519, 67.40363715,
       68.42572932, 77.04685456, 73.53619016, 71.22537308, 71.93639372,
       74.60272112, 74.06945564, 69.98108697, 76.78022182, 72.33634283,
       77.00241577, 71.80307735, 61.80434963, 76.29139513, 75.98

###### 2)Check the R squared score

In [15]:
from sklearn.metrics import r2_score
r2 = r2_score(k, y_predi)

In [16]:
print('R2 score is',r2)

R2 score is 0.6192442167740035


#### 3)Split the dataset into training and testing sets.

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(l, y, test_size = 0.1, random_state=11)

NameError: name 'X' is not defined

In [25]:
X_train

array([[2.86],
       [2.38],
       [2.73],
       [1.57],
       [3.48],
       [5.25],
       [1.96],
       [2.54],
       [2.15],
       [2.73],
       [2.61],
       [2.  ],
       [4.91],
       [2.12],
       [1.63],
       [1.99],
       [5.34],
       [5.06],
       [2.44],
       [4.79],
       [2.2 ],
       [1.31],
       [3.7 ],
       [1.92],
       [3.5 ],
       [3.05],
       [2.43],
       [1.39],
       [2.46],
       [5.1 ],
       [4.88],
       [2.95],
       [2.92],
       [2.64],
       [5.16],
       [2.11],
       [3.26],
       [2.04],
       [1.49],
       [2.9 ],
       [6.48],
       [1.87],
       [2.89],
       [1.34],
       [5.54],
       [1.82],
       [1.88],
       [2.74],
       [1.43],
       [5.54],
       [1.89],
       [2.41],
       [6.02],
       [3.06],
       [3.85],
       [1.37],
       [1.33],
       [4.19],
       [1.43],
       [5.13],
       [1.43],
       [2.05],
       [5.31],
       [1.89],
       [6.04],
       [6.82],
       [1.

In [26]:
X_test

array([[4.07],
       [1.85],
       [1.33],
       [1.79],
       [1.83],
       [5.17],
       [3.7 ],
       [2.51],
       [2.24],
       [1.91],
       [1.49],
       [5.78],
       [7.06],
       [1.46]])

In [17]:
Y_train

NameError: name 'Y_train' is not defined

In [28]:
Y_test

array([58.2, 79.4, 73.8, 72.1, 75.3, 56.6, 69.5, 66.1, 75.5, 79.7, 67.6,
       51.4, 56.7, 79.5])

In [38]:
r2_2 = r2_score(Y_train, y_train_predict)
r2_2

0.6058059705936719

In [39]:
lr.fit(X_test, Y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [40]:
y_test_predict = lr.predict(X_test)
r2_3 = r2_score(Y_test, y_test_predict)
r2_3

0.7417105740991836

# 5)Finally take any value for fertility and predict the life.

In [44]:
finall = lr.predict([[2.73]])

In [45]:
finall

array([69.93822334])